name: Dev Build and Publish

on:
  push:
    branches:
    - master

jobs:
  build-for-dev:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/factory.yml
    with:
      tag: ${{ github.ref_name }}-head
      push: true
    secrets: inherit