name: Pull Request Build

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-for-dev:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/factory.yml
    with:
      tag: pr-${{ github.event.number }}
      push: false
    secrets: inherit