name: Release Build and Publish

on:
  release:
    types:
    - published

jobs:
  build-for-release:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/factory.yml
    with:
      tag: ${{ github.ref_name }}
      push: true
    secrets: inherit
